### PR TITLE
Fix merging issues

### PR DESCRIPTION
**Pull request by JeeH-K**
fix issues from merging FLASHViewer+FLASHTagger

### CODE REVIEW

**Comment by t0mdavid-m** [comment]
I fixed some issues I noticed during running the app but overall the changes look good to me!

I will follow up with further feedback but I think this addresses all urgent changes needed to get a first working version. Thank you!

**Comment by t0mdavid-m** [comment]
For some reason, the `FLASHDeconvViewer` Vue.JS component crashes if I select `example_spectrum_1.mzml`. Any idea why this could be the case? No such issue occurs for the example data provided in the `FileUpload` section.

**Comment by JeeH-K** [comment]
> For some reason, the `FLASHDeconvViewer` Vue.JS component crashes if I select `example_spectrum_1.mzml`. Any idea why this could be the case? No such issue occurs for the example data provided in the `FileUpload` section.

Do you mean after running FLASHDeconv? I don't have the output files from it, so have not tested yet

**Comment by t0mdavid-m** [comment]
> > For some reason, the `FLASHDeconvViewer` Vue.JS component crashes if I select `example_spectrum_1.mzml`. Any idea why this could be the case? No such issue occurs for the example data provided in the `FileUpload` section.
> 
> Do you mean after running FLASHDeconv? I don't have the output files from it, so have not tested yet

Yes after running FLASHDeconv. If you select default parameters in the workflow section and the provided example file, the browser crashes upon viewing. Provided you have FLASHDeconv in the path you should be able to run the workflow in the WebApp.

**Pull request merged**
